# Generated by Django 5.1.7 on 2025-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
