# Generated by Django 5.1.7 on 2025-04-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from district admin review'),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted')], default='pending', max_length=20),
        ),
    ]
